# Generated by Django 4.1.1 on 2022-10-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_name_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='description', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default='10'),
        ),
    ]
